### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by Quitino** [PaoPaoRobot/PaoPaoRobotTutorial#6]
十分感谢泡泡机器人团队的付出，要是在组员以及元老介绍时加上他们个人的github账号链接就更完美了。不过这也是一项十分繁琐的工作。

**Comment by ljjyxz123** [comment]
> 十分感谢泡泡机器人团队的付出，要是在组员以及元老介绍时加上他们个人的github账号链接就更完美了。不过这也是一项十分繁琐的工作。

谢谢你的建议！

**Comment by OptSolution** [comment]
个人认为，泡泡团队的人github账户应该都有加入到这个github组织里面，可以从这个组织成员直接找到愿意公开github的个人。没有公开公开在组织中显示的个人可以认为他们没有这个意愿也不用强求。
不过账号和人不见得可以很容易的对应上就是了

**Comment by Quitino** [comment]
> 个人认为，泡泡团队的人github账户应该都有加入到这个github组织里面，可以从这个组织成员直接找到愿意公开github的个人。没有公开公开在组织中显示的个人可以认为他们没有这个意愿也不用强求。
> 不过账号和人不见得可以很容易的对应上就是了

好的好的，感谢感谢.
